# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  target 'RxListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxListUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
