# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MartAPIMockup' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MartAPIMockup

	pod 'RxSwift'

  target 'MartAPIMockupTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MartAPIMockupUITests' do
    # Pods for testing
  end

end
